siteTitle="myGNOME"
baseColor = "#00BCD4"
linkPrefix = "/myGNOME"
docPages = [
  "/docs/",
  "/docs/extensions/",
  "/docs/configuration/",
  "/docs/terminal/",
  "/docs/linux/",
  "/docs/ubuntu/",
]
